<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <RootNamespace>Wolfgang.Conflict.Core</RootNamespace>
    <AssemblyName>Wolfgang.Conflict.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wolfgang.Conflict.Core.Tests.Unit" />
  </ItemGroup>

</Project>
